spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # EC2에서 직접 RDS 엔드포인트로 접속
    url: jdbc:mysql://senicle-rds-database.cxxlveyko9rd.ap-northeast-2.rds.amazonaws.com:3306/${DB_NAME:senicle_db}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# production 환경에서 이것으로 변경
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: false
#        show_sql: false
#    open-in-view: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true)
    open-in-view: true

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2

logging:
  level:
    org.springframework.security: INFO
    com.seniclass.server: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
