server:
  port: 8080

spring:
  application:
    name: server
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      password: # 비밀번호가 있다면 설정
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      file-size-threshold: 2KB

# Actuator 헬스체크 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  api-docs:
    path: /api-docs

# JWT 설정
jwt:
  secret: ${JWT_SECRET:seniclass-jwt-secret-key-that-should-be-changed-in-production-environment}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:3600000}  # 1시간 (밀리초)
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:2592000000}  # 30일 (밀리초)

# 로그 설정 추가
logging:
  level:
    com.seniclass.server.domain.auth: DEBUG
    org.springframework.data.redis: DEBUG
    root: INFO

# 파일 저장 설정
file:
  upload-dir: ./uploads/assignments
  max-file-size: 52428800  # 50MB in bytes

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:senicle-bucket}
    enabled: ${AWS_S3_ENABLED:true}  # S3 사용 여부 (false면 로컬 저장소 사용)
