name: "✨ Feature"
description: 새로운 기능 추가를 위한 이슈 템플릿
title: "[FEATURE] - "
labels: ["feature"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 📌 Description
      description: 추가할 기능에 대해 설명해주세요
      placeholder: 추가할 기능의 목적과 내용을 자세히 설명해주세요
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: 기능 완료를 위한 조건들
      placeholder: |
        - [ ] 기능 구현 완료
        - [ ] 단위 테스트 작성
        - [ ] 통합 테스트 통과
        - [ ] UI/UX 검토 완료
      value: |
        - [ ]
        - [ ]
        - [ ]

  - type: textarea
    id: notes
    attributes:
      label: 📝 Notes
      description: 추가 정보나 참고사항
      placeholder: 추가 정보나 참고사항을 입력하세요
